name: cropscan_pro
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  cached_network_image: ^3.3.1
  camera: ^0.11.1
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  fl_chart: ^0.65.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  image: ^4.5.4
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^11.0.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  sizer: ^2.0.15
  sqflite: ^2.4.2
  tflite_flutter: ^0.11.0
  web: any
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/ml_models/converted_model.tflite
    - assets/ml_models/labels.txt
